name: Deploy to Firebase Functions via github action
"on":
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      CI: false
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase
        run: npm install -g firebase-tools

      - name: Download deps
        working-directory: firebase/functions
        run: npm install

      - name: Deploy
        working-directory: firebase/functions
        run: firebase deploy --token $FIREBASE_TOKEN
