name: Deploy to Firebase Functions via github action
"on":
  push:
    branches:
      - main
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download deps
        working-directory: firebase/functions
        run: npm install

      - name: Deploy
        run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
